// Generated by tools/b4/gen_ioaf2_headers.py from the KDK 14.8.9 (23J631)
// AppleGraphicsDeviceControl + AppleParavirtGPU binaries. Do not edit by hand.
#pragma once
#pragma clang diagnostic ignored "-Winconsistent-missing-override"
#pragma clang diagnostic ignored "-Woverloaded-virtual"
#pragma clang diagnostic ignored "-Wmismatched-tags"
#pragma clang diagnostic ignored "-Wunused-private-field"
#include <IOKit/IOService.h>
#include <IOKit/IOUserClient.h>
#include <IOKit/graphics/IOAccelerator.h>

class AGDCClientState_t;

class AppleGraphicsDeviceControl;

// AppleGraphicsDeviceControl : IOService   sizeof 0x110, 276 vtable slots
class AppleGraphicsDeviceControl : public IOService {
    OSDeclareDefaultStructors(AppleGraphicsDeviceControl)
public:
    virtual bool start(IOService*);   // [184]
    virtual void stop(IOService*);   // [185]
    virtual bool terminate(unsigned int);   // [192]
    virtual IOReturn message(unsigned int, IOService*, void*);   // [230]
    virtual IOReturn newUserClient(task*, void*, unsigned int, OSDictionary*, IOUserClient**);   // [238]
    virtual void * vendor_doDeviceAttribute(unsigned int, unsigned long*, unsigned long, unsigned long*, unsigned long*, IOExternalMethodArguments*) = 0;   // [266] pure
    virtual void * vendor_doDeviceAttribute(unsigned int, unsigned long*, unsigned long, unsigned long*, unsigned long*, AGDCClientState_t*);   // [267]
    virtual void * _RESERVEDAppleGraphicsDeviceControl0();   // [268]
    virtual void * _RESERVEDAppleGraphicsDeviceControl1();   // [269]
    virtual void * _RESERVEDAppleGraphicsDeviceControl2();   // [270]
    virtual void * _RESERVEDAppleGraphicsDeviceControl3();   // [271]
    virtual void * _RESERVEDAppleGraphicsDeviceControl4();   // [272]
    virtual void * _RESERVEDAppleGraphicsDeviceControl5();   // [273]
    virtual void * _RESERVEDAppleGraphicsDeviceControl6();   // [274]
    virtual void * _RESERVEDAppleGraphicsDeviceControl7();   // [275]
protected:
    uint8_t _nvData[0x110 - sizeof(IOService)];
};
static_assert(sizeof(AppleGraphicsDeviceControl) == 0x110, "AppleGraphicsDeviceControl layout");

