// Generated by tools/b4/gen_ioaf2_headers.py from the KDK 14.8.9 (23J631)
// IOAcceleratorFamily2 + AppleParavirtGPU binaries. Do not edit by hand.
#pragma once
#pragma clang diagnostic ignored "-Winconsistent-missing-override"
#pragma clang diagnostic ignored "-Woverloaded-virtual"
#pragma clang diagnostic ignored "-Wmismatched-tags"
#pragma clang diagnostic ignored "-Wunused-private-field"
#include <IOKit/IOService.h>
#include <IOKit/IOUserClient.h>
#include <IOKit/graphics/IOAccelerator.h>

class IOAccelAllocationInfo;
class IOAccelClientSharedRO;
class IOAccelClientSharedRW;
class IOAccelCommandDescriptor;
class IOAccelConfig;
class IOAccelDeviceShmem;
class IOAccelDisplayPipe;
class IOAccelEvent;
class IOAccelEventFence;
class IOAccelEventQueue;
class IOAccelGetResourceInfoReturnData;
class IOAccelKernelCommand;
class IOAccelNewResourceArgs;
class IOAccelResourcePrivate;
class IOAccelSegmentResourceList;
class IOAccelSegmentResourceListHeader;
class IOAccelSurface;
class IOFramebuffer;
class IOPCIDevice;
class IORangeAllocator;
class IOSurface;
enum eIOAccelCommandQueuePriority : unsigned int;
class vendevtBarrierRec;
class vendevtCommandRec;

class IOGraphicsAccelerator2;
class IOAccelEventMachine2;
class IOAccelEventMachineFast2;
class IOAccelMemory;
class IOAccelSysMemory;
class IOAccelVidMemory;
class IOAccelMemoryMap;
class IOAccelResource2;
class IOAccelTask;
class IOAccelSubmitter2;
class IOAccelCommandQueue;
class IOAccelChannel2;
class IOAccelFIFOChannel2;
class IOAccelShared2;
class IOAccelSharedUserClient2;
class IOAccelDisplayMachine;

// IOGraphicsAccelerator2 : IOAccelerator   sizeof 0xdd8, 350 vtable slots
class IOGraphicsAccelerator2 : public IOAccelerator {
    OSDeclareDefaultStructors(IOGraphicsAccelerator2)
public:
    virtual void free();   // [18]
    virtual IOReturn setProperties(OSObject*);   // [96]
    virtual bool requestTerminate(IOService*, unsigned int);   // [127]
    virtual bool didTerminate(IOService*, unsigned int, bool*);   // [129]
    virtual IOReturn configureReport(IOReportChannelList*, unsigned int, void*, void*);   // [133]
    virtual IOReturn updateReport(IOReportChannelList*, unsigned int, void*, void*);   // [134]
    virtual bool start(IOService*);   // [184]
    virtual void stop(IOService*);   // [185]
    virtual bool terminate(unsigned int);   // [192]
    virtual bool finalize(unsigned int);   // [193]
    virtual IOWorkLoop * getWorkLoop() const;   // [209]
    virtual IOReturn requestProbe(unsigned int);   // [229]
    virtual IOReturn message(unsigned int, IOService*, void*);   // [230]
    virtual IOReturn newUserClient(task*, void*, unsigned int, IOUserClient**);   // [239]
    virtual void * acceleratorDidLock(char const*, int);   // [266]
    virtual void * acceleratorWillUnlock(char const*, int);   // [267]
    virtual void * tmpTotalVRAM();   // [268]
    virtual void * totalTextureMemory();   // [269]
    virtual void * isIdle();   // [270]
    virtual IOMemoryDescriptor * getStampMemory(unsigned int*) = 0;   // [271] pure
    virtual void * createEventMachine();   // [272]
    virtual IOAccelEventMachine2 * newEventMachine() = 0;   // [273] pure
    virtual void * newClientSharedRO();   // [274]
    virtual void * newClientSharedRW();   // [275]
    virtual void * deleteClientSharedRO(IOAccelClientSharedRO*);   // [276]
    virtual void * deleteClientSharedRW(IOAccelClientSharedRW*);   // [277]
    virtual void * createShared(task*);   // [278]
    virtual void * createSysMemory();   // [279]
    virtual void * createVidMemory(IOAccelShared2*, IOAccelResource2*, unsigned long long, void*);   // [280]
    virtual void * createMemoryMap(IOAccelTask*, IOAccelMemory*, unsigned int);   // [281]
    virtual void * createResource(IOAccelShared2*, unsigned int);   // [282]
    virtual void * createCommandDescriptor();   // [283]
    virtual void * deleteCommandDescriptor(IOAccelCommandDescriptor*);   // [284]
    virtual void * newBlockFence();   // [285]
    virtual void * scrubEvents();   // [286]
    virtual void * createDrawable(IOAccelSurface*, IOAccelShared2*, bool);   // [287]
    virtual void * resourceTypeForIOSurface(IOSurface*);   // [288]
    virtual void * createDisplayPipe(IOFramebuffer*, unsigned int);   // [289]
    virtual void * createMemoryDescriptorWithAddressRange(unsigned long long, unsigned long long, unsigned int, task*);   // [290]
    virtual void * createMemoryDescriptorWithPersistentMemoryDescriptor(IOMemoryDescriptor*);   // [291]
    virtual void * createBufferMemoryDescriptorWithOptions(unsigned int, unsigned long, unsigned long);   // [292]
    virtual void * createBufferMemoryDescriptorInTaskWithOptions(task*, unsigned int, unsigned long, unsigned long);   // [293]
    virtual void * freeAllGPUMappings();   // [294]
    virtual void * freeWaitToPrepareVidMemory(IOAccelVidMemory*, bool, bool);   // [295]
    virtual void * freeWaitToPrepareVidMap(IOAccelMemoryMap*, bool, bool);   // [296]
    virtual void * unwireAllVidMemory();   // [297]
    virtual void * freeAllVidMemoryMappings();   // [298]
    virtual void * pageoffSurfaceInLinear();   // [299]
    virtual void * freeWaitToPrepareSysMemory(IOAccelSysMemory*, bool);   // [300]
    virtual void * freeWaitToPrepareSysMap(IOAccelMemoryMap*, bool);   // [301]
    virtual void * collectGartWirings();   // [302]
    virtual void * unwireAllSysMemory();   // [303]
    virtual void * freeAllSysMemoryMappings();   // [304]
    virtual void * getMaxSingleSysMemorySize();   // [305]
    virtual void * getMaxWiredSysMemorySize();   // [306]
    virtual IOAccelTask * createUserGPUTask() = 0;   // [307] pure
    virtual void * acceleratorFinalize();   // [308]
    virtual void * submitSwapCopy(IOAccelEvent*, IOAccelResource2*, IOAccelResource2*);   // [309]
    virtual void populateAccelConfig(IOAccelConfig*) = 0;   // [310] pure
    virtual void * calcMaxGPUPhysicalMemoryBytes(unsigned long long);   // [311]
    virtual bool configureDevice(IOPCIDevice*) = 0;   // [312] pure
    virtual void teardownDevice(IOPCIDevice*) = 0;   // [313] pure
    virtual IOAccelTask * createKernelGPUTask() = 0;   // [314] pure
    virtual void * systemWillSleep();   // [315]
    virtual void * systemDidWake();   // [316]
    virtual void * systemWillChangeSpeed();   // [317]
    virtual void * systemDidChangeSpeed();   // [318]
    virtual void * configIsHeadless();   // [319]
    virtual IOAccelDisplayMachine * newDisplayMachine() = 0;   // [320] pure
    virtual IOAccelShared2 * newShared();   // [321]
    virtual IOAccelSharedUserClient2 * newSharedUserClient();   // [322]
    virtual void * newDevice();   // [323]
    virtual IOService * newGLContext() = 0;   // [324] pure
    virtual IOService * newCLContext() = 0;   // [325] pure
    virtual IOService * newSurface() = 0;   // [326] pure
    virtual IOService * new2DContext() = 0;   // [327] pure
    virtual IOService * newVideoContext() = 0;   // [328] pure
    virtual IOAccelDisplayPipe * newDisplayPipe();   // [329]
    virtual void * newDrawable();   // [330]
    virtual void * newContext(unsigned int);   // [331]
    virtual IOAccelSysMemory * newSysMemory() = 0;   // [332] pure
    virtual IOAccelVidMemory * newVidMemory() = 0;   // [333] pure
    virtual IOAccelResource2 * newResource() = 0;   // [334] pure
    virtual void * newCommandDescriptor();   // [335]
    virtual void * newStatistics();   // [336]
    virtual IOAccelMemoryMap * newMemoryMap() = 0;   // [337] pure
    virtual void * getMaxResourceSize();   // [338]
    virtual void * newRemoteMemory();   // [339]
    virtual void * createRemoteMemory(IOAccelShared2*, unsigned long long, unsigned int, unsigned int);   // [340]
    virtual void * newContextEventFence();   // [341]
    virtual void * createIODMACommand();   // [342]
    virtual void * triage(char**, unsigned long long*);   // [343]
    virtual void * _RESERVEDIOGraphicsAccelerator3();   // [344]
    virtual void * _RESERVEDIOGraphicsAccelerator4();   // [345]
    virtual void * _RESERVEDIOGraphicsAccelerator5();   // [346]
    virtual void * describeDriverAllocations(IOAccelAllocationInfo*);   // [347]
    virtual IOAccelCommandQueue * newCommandQueue();   // [348]
    virtual void * ktraceStateChanged();   // [349]
protected:
    uint8_t _nvData[0xdd8 - sizeof(IOAccelerator)];
};
static_assert(sizeof(IOGraphicsAccelerator2) == 0xdd8, "IOGraphicsAccelerator2 layout");

// IOAccelEventMachine2 : OSObject   sizeof 0xf0, 84 vtable slots
class IOAccelEventMachine2 : public OSObject {
    OSDeclareDefaultStructors(IOAccelEventMachine2)
public:
    virtual void free();   // [18]
    virtual bool init(IOGraphicsAccelerator2*, unsigned int, int);   // [35]
    virtual void * getClientTestEventFunc() = 0;   // [36] pure
    virtual void * getNumStamps();   // [37]
    virtual void * setStampBaseAddress(unsigned int volatile*);   // [38]
    virtual void * getStampOffset(int);   // [39]
    virtual void * initEvent(IOAccelEvent*) = 0;   // [40] pure
    virtual void * cleanEvent(IOAccelEvent*) = 0;   // [41] pure
    virtual void * finishStamp(int) = 0;   // [42] pure
    virtual void * finishAllStamps() = 0;   // [43] pure
    virtual void * testStamp(int) = 0;   // [44] pure
    virtual void * testAllStamps() = 0;   // [45] pure
    virtual void * testAllStampsUnlocked() = 0;   // [46] pure
    virtual void * finishEventUnlocked(IOAccelEvent*) = 0;   // [47] pure
    virtual void * testEventUnlocked(IOAccelEvent*) = 0;   // [48] pure
    virtual void * finishEvent(IOAccelEvent*) = 0;   // [49] pure
    virtual void * testEvent(IOAccelEvent*) = 0;   // [50] pure
    virtual void * finishEventExcluding(IOAccelEvent*, int) = 0;   // [51] pure
    virtual void * testEventExcluding(IOAccelEvent*, int) = 0;   // [52] pure
    virtual void * moveEvent(IOAccelEvent*, IOAccelEvent*) = 0;   // [53] pure
    virtual void * copyEvent(IOAccelEvent*, IOAccelEvent*) = 0;   // [54] pure
    virtual void * mergeEvent(IOAccelEvent*, IOAccelEvent*) = 0;   // [55] pure
    virtual void * copyEventExcluding(IOAccelEvent*, IOAccelEvent*, int) = 0;   // [56] pure
    virtual void * mergeEventExcluding(IOAccelEvent*, IOAccelEvent*, int) = 0;   // [57] pure
    virtual void * setEventStamp(int, IOAccelEvent*) = 0;   // [58] pure
    virtual void * incrementStamp(int) = 0;   // [59] pure
    virtual void * writeStampCommand(int, IOAccelEventQueue*, vendevtCommandRec*) = 0;   // [60] pure
    virtual void * writeEventStampCommand(int, IOAccelEventQueue*, IOAccelEvent*, vendevtCommandRec*) = 0;   // [61] pure
    virtual void * writeEventBarrierCommand(IOAccelEventQueue*, IOAccelEvent*, vendevtBarrierRec*, int) = 0;   // [62] pure
    virtual void * logCommandSubmission(int) = 0;   // [63] pure
    virtual void * stampIsIncremented() = 0;   // [64] pure
    virtual void * getStamp(int) = 0;   // [65] pure
    virtual void * checkGPUProgress() = 0;   // [66] pure
    virtual void * checkChannelProgress(int) = 0;   // [67] pure
    virtual void * eventTimeout(int) = 0;   // [68] pure
    virtual void * signalStamp(int, unsigned int);   // [69]
    virtual void * collectAllLiveEventIfNeeded();   // [70]
    virtual void * waitForStamp(int, unsigned int, unsigned int*);   // [71]
    virtual void * enableStampInterrupt(int);   // [72]
    virtual void * disableStampInterrupt(int);   // [73]
    virtual void * deviceTerminatedUnlocked();   // [74]
    virtual void * enableEventStampInterrupts(IOAccelEvent const*) = 0;   // [75] pure
    virtual void * disableEventStampInterrupts(IOAccelEvent const*) = 0;   // [76] pure
    virtual void stop();   // [77]
    virtual void * scrubEvent(IOAccelEvent*) = 0;   // [78] pure
    virtual void * triage(char**, unsigned long long*) = 0;   // [79] pure
    virtual void * _RESERVEDIOAccelEventMachine2();   // [80]
    virtual void * _RESERVEDIOAccelEventMachine3();   // [81]
    virtual void * _RESERVEDIOAccelEventMachine4();   // [82]
    virtual void * _RESERVEDIOAccelEventMachine5();   // [83]
protected:
    uint8_t _nvData[0xf0 - sizeof(OSObject)];
};
static_assert(sizeof(IOAccelEventMachine2) == 0xf0, "IOAccelEventMachine2 layout");

// IOAccelEventMachineFast2 : IOAccelEventMachine2   sizeof 0xd30, 95 vtable slots
class IOAccelEventMachineFast2 : public IOAccelEventMachine2 {
    OSDeclareDefaultStructors(IOAccelEventMachineFast2)
public:
    virtual void free();   // [18]
    virtual bool init(IOGraphicsAccelerator2*, unsigned int, int);   // [35]
    virtual void * getClientTestEventFunc();   // [36]
    virtual void * initEvent(IOAccelEvent*);   // [40]
    virtual void * cleanEvent(IOAccelEvent*);   // [41]
    virtual void * finishStamp(int);   // [42]
    virtual void * finishAllStamps();   // [43]
    virtual void * testStamp(int);   // [44]
    virtual void * testAllStamps();   // [45]
    virtual void * testAllStampsUnlocked();   // [46]
    virtual void * finishEventUnlocked(IOAccelEvent*);   // [47]
    virtual void * testEventUnlocked(IOAccelEvent*);   // [48]
    virtual void * finishEvent(IOAccelEvent*);   // [49]
    virtual void * testEvent(IOAccelEvent*);   // [50]
    virtual void * finishEventExcluding(IOAccelEvent*, int);   // [51]
    virtual void * testEventExcluding(IOAccelEvent*, int);   // [52]
    virtual void * moveEvent(IOAccelEvent*, IOAccelEvent*);   // [53]
    virtual void * copyEvent(IOAccelEvent*, IOAccelEvent*);   // [54]
    virtual void * mergeEvent(IOAccelEvent*, IOAccelEvent*);   // [55]
    virtual void * copyEventExcluding(IOAccelEvent*, IOAccelEvent*, int);   // [56]
    virtual void * mergeEventExcluding(IOAccelEvent*, IOAccelEvent*, int);   // [57]
    virtual void * setEventStamp(int, IOAccelEvent*);   // [58]
    virtual void * incrementStamp(int);   // [59]
    virtual void * writeStampCommand(int, IOAccelEventQueue*, vendevtCommandRec*);   // [60]
    virtual void * writeEventStampCommand(int, IOAccelEventQueue*, IOAccelEvent*, vendevtCommandRec*);   // [61]
    virtual void * writeEventBarrierCommand(IOAccelEventQueue*, IOAccelEvent*, vendevtBarrierRec*, int);   // [62]
    virtual void * logCommandSubmission(int);   // [63]
    virtual void * stampIsIncremented();   // [64]
    virtual void * getStamp(int);   // [65]
    virtual void * checkGPUProgress();   // [66]
    virtual void * checkChannelProgress(int);   // [67]
    virtual void * eventTimeout(int);   // [68]
    virtual void * deviceTerminatedUnlocked();   // [74]
    virtual void * enableEventStampInterrupts(IOAccelEvent const*);   // [75]
    virtual void * disableEventStampInterrupts(IOAccelEvent const*);   // [76]
    virtual void * scrubEvent(IOAccelEvent*);   // [78]
    virtual void * triage(char**, unsigned long long*);   // [79]
    virtual void * writeStamp(int, vendevtCommandRec*, unsigned int) = 0;   // [84] pure
    virtual void * prepareBarrier(vendevtBarrierRec*) = 0;   // [85] pure
    virtual void * completeBarrier(vendevtBarrierRec*) = 0;   // [86] pure
    virtual void * writeBarrierElement(vendevtBarrierRec*, int, unsigned int) = 0;   // [87] pure
    virtual void * waitForAnyStamp(IOAccelEvent*, int*);   // [88]
    virtual void * _RESERVEDIOAccelEventMachineFast0();   // [89]
    virtual void * _RESERVEDIOAccelEventMachineFast1();   // [90]
    virtual void * _RESERVEDIOAccelEventMachineFast2();   // [91]
    virtual void * _RESERVEDIOAccelEventMachineFast3();   // [92]
    virtual void * _RESERVEDIOAccelEventMachineFast4();   // [93]
    virtual void * _RESERVEDIOAccelEventMachineFast5();   // [94]
protected:
    uint8_t _nvData[0xd30 - sizeof(IOAccelEventMachine2)];
};
static_assert(sizeof(IOAccelEventMachineFast2) == 0xd30, "IOAccelEventMachineFast2 layout");

// IOAccelMemory : OSObject   sizeof 0xb0, 60 vtable slots
class IOAccelMemory : public OSObject {
    OSDeclareDefaultStructors(IOAccelMemory)
public:
    virtual void release() const;   // [5]
    virtual void free();   // [18]
    virtual bool init(IOGraphicsAccelerator2*);   // [35]
    virtual void * getLength() const;   // [36]
    virtual void * getDirtySize() const = 0;   // [37] pure
    virtual void * getResidentSize() const = 0;   // [38] pure
    virtual void * createMappingInTask(IOAccelTask*, unsigned int);   // [39]
    virtual void * createMappingInTaskAtAddressLength(IOAccelTask*, unsigned int, unsigned long long, unsigned long long);   // [40]
    virtual void * prepare();   // [41]
    virtual void * complete();   // [42]
    virtual void * getPhysicalSegment(unsigned long long, unsigned long long*) = 0;   // [43] pure
    virtual void * setPurgeable(unsigned int, unsigned int*) = 0;   // [44] pure
    virtual void * setTag(unsigned int) = 0;   // [45] pure
    virtual void * getTag() = 0;   // [46] pure
    virtual void * matchForReuse(void*, unsigned long long) = 0;   // [47] pure
    virtual void * _RESERVEDIOAccelMemory0();   // [48]
    virtual void * _RESERVEDIOAccelMemory1();   // [49]
    virtual void * _RESERVEDIOAccelMemory2();   // [50]
    virtual void * _RESERVEDIOAccelMemory3();   // [51]
    virtual void * _RESERVEDIOAccelMemory4();   // [52]
    virtual void * _RESERVEDIOAccelMemory5();   // [53]
    virtual void * wire() = 0;   // [54] pure
    virtual void * unwire() = 0;   // [55] pure
    virtual void * orphanIt();   // [56]
    virtual void * unorphanIt(IOAccelShared2*);   // [57]
    virtual void * increment_wire_count() = 0;   // [58] pure
    virtual void * decrement_wire_count() = 0;   // [59] pure
protected:
    uint8_t _nvData[0xb0 - sizeof(OSObject)];
};
static_assert(sizeof(IOAccelMemory) == 0xb0, "IOAccelMemory layout");

// IOAccelSysMemory : IOAccelMemory   sizeof 0x198, 66 vtable slots
class IOAccelSysMemory : public IOAccelMemory {
    OSDeclareDefaultStructors(IOAccelSysMemory)
public:
    virtual void free();   // [18]
    virtual bool init(IOGraphicsAccelerator2*);   // [35]
    virtual void * getDirtySize() const;   // [37]
    virtual void * getResidentSize() const;   // [38]
    virtual void * complete();   // [42]
    virtual void * getPhysicalSegment(unsigned long long, unsigned long long*);   // [43]
    virtual void * setPurgeable(unsigned int, unsigned int*);   // [44]
    virtual void * setTag(unsigned int);   // [45]
    virtual void * getTag();   // [46]
    virtual void * matchForReuse(void*, unsigned long long);   // [47]
    virtual void * wire();   // [54]
    virtual void * unwire();   // [55]
    virtual void * orphanIt();   // [56]
    virtual void * unorphanIt(IOAccelShared2*);   // [57]
    virtual void * increment_wire_count();   // [58]
    virtual void * decrement_wire_count();   // [59]
    virtual void * _RESERVEDIOAccelSysMemory0();   // [60]
    virtual void * _RESERVEDIOAccelSysMemory1();   // [61]
    virtual void * _RESERVEDIOAccelSysMemory2();   // [62]
    virtual void * _RESERVEDIOAccelSysMemory3();   // [63]
    virtual void * _RESERVEDIOAccelSysMemory4();   // [64]
    virtual void * _RESERVEDIOAccelSysMemory5();   // [65]
protected:
    uint8_t _nvData[0x198 - sizeof(IOAccelMemory)];
};
static_assert(sizeof(IOAccelSysMemory) == 0x198, "IOAccelSysMemory layout");

// IOAccelVidMemory : IOAccelMemory   sizeof 0x110, 69 vtable slots
class IOAccelVidMemory : public IOAccelMemory {
    OSDeclareDefaultStructors(IOAccelVidMemory)
public:
    virtual void free();   // [18]
    virtual void * getDirtySize() const;   // [37]
    virtual void * getResidentSize() const;   // [38]
    virtual void * prepare();   // [41]
    virtual void * complete();   // [42]
    virtual void * getPhysicalSegment(unsigned long long, unsigned long long*) = 0;   // [43] pure
    virtual void * setPurgeable(unsigned int, unsigned int*);   // [44]
    virtual void * setTag(unsigned int);   // [45]
    virtual void * getTag();   // [46]
    virtual void * matchForReuse(void*, unsigned long long);   // [47]
    virtual void * wire();   // [54]
    virtual void * unwire();   // [55]
    virtual void * orphanIt();   // [56]
    virtual void * unorphanIt(IOAccelShared2*);   // [57]
    virtual void * increment_wire_count();   // [58]
    virtual void * decrement_wire_count();   // [59]
    virtual bool init(IOGraphicsAccelerator2*, IOAccelShared2*, IOAccelResource2*, unsigned long long, void*);   // [60]
    virtual void * allocPhysical() = 0;   // [61] pure
    virtual void * deallocPhysical() = 0;   // [62] pure
    virtual void * _RESERVEDIOAccelVidMemory0();   // [63]
    virtual void * _RESERVEDIOAccelVidMemory1();   // [64]
    virtual void * _RESERVEDIOAccelVidMemory2();   // [65]
    virtual void * _RESERVEDIOAccelVidMemory3();   // [66]
    virtual void * _RESERVEDIOAccelVidMemory4();   // [67]
    virtual void * _RESERVEDIOAccelVidMemory5();   // [68]
protected:
    uint8_t _nvData[0x110 - sizeof(IOAccelMemory)];
};
static_assert(sizeof(IOAccelVidMemory) == 0x110, "IOAccelVidMemory layout");

// IOAccelMemoryMap : OSObject   sizeof 0x118, 57 vtable slots
class IOAccelMemoryMap : public OSObject {
    OSDeclareDefaultStructors(IOAccelMemoryMap)
public:
    virtual void release() const;   // [5]
    virtual void free();   // [18]
    virtual bool init(IOGraphicsAccelerator2*, IOAccelTask*, IOAccelMemory*, unsigned int);   // [35]
    virtual void * matchOptionBits(unsigned int);   // [36]
    virtual void * getGPUVirtualAddress();   // [37]
    virtual void * getGPUVirtualAddressForUserProcess();   // [38]
    virtual void * prepare();   // [39]
    virtual void * complete();   // [40]
    virtual void * compatibleWith(IOAccelMemoryMap*);   // [41]
    virtual void * allocGPUVirtualAddress();   // [42]
    virtual void * reserveGPUVirtualAddress(unsigned long long, unsigned long long);   // [43]
    virtual void * freeGPUVirtualAddress();   // [44]
    virtual void * getLength() const;   // [45]
    virtual void * commitIntoGPUPageTable() = 0;   // [46] pure
    virtual void * releaseFromGPUPageTable() = 0;   // [47] pure
    virtual void * updateGPUPageTable() = 0;   // [48] pure
    virtual void * getGPUVirtualAddressLengthForUserProcess();   // [49]
    virtual void * getAssignedGPUVirtualAddressLength() const;   // [50]
    virtual void * _RESERVEDIOAccelMemoryMap1();   // [51]
    virtual void * _RESERVEDIOAccelMemoryMap2();   // [52]
    virtual void * _RESERVEDIOAccelMemoryMap3();   // [53]
    virtual void * _RESERVEDIOAccelMemoryMap4();   // [54]
    virtual void * _RESERVEDIOAccelMemoryMap5();   // [55]
    virtual void * redirect(IOAccelMemory*);   // [56]
protected:
    uint8_t _nvData[0x118 - sizeof(OSObject)];
};
static_assert(sizeof(IOAccelMemoryMap) == 0x118, "IOAccelMemoryMap layout");

// IOAccelResource2 : OSObject   sizeof 0x180, 79 vtable slots
class IOAccelResource2 : public OSObject {
    OSDeclareDefaultStructors(IOAccelResource2)
public:
    virtual int getRetainCount() const;   // [3]
    virtual void retain() const;   // [4]
    virtual void release() const;   // [5]
    virtual void free();   // [18]
    virtual void * initSurfaceBuffer(IOAccelSurface*, unsigned int, unsigned int, unsigned int, unsigned int, unsigned int);   // [35]
    virtual void * allocMemory(IOAccelShared2*);   // [36]
    virtual void * allocDataBufferMemory(IOAccelShared2*, bool, unsigned int);   // [37]
    virtual void * allocFallbackMemory();   // [38]
    virtual bool init(IOGraphicsAccelerator2*, IOAccelShared2*, unsigned int);   // [39]
    virtual void * initialize(IOAccelNewResourceArgs*, unsigned long long);   // [40]
    virtual void * initClientShared(IOAccelClientSharedRO*, IOAccelClientSharedRW*);   // [41]
    virtual void * termClientShared(IOAccelClientSharedRO*, IOAccelClientSharedRW*);   // [42]
    virtual void * copyResourcePrivate(IOAccelResourcePrivate*);   // [43]
    virtual void * sharedRelease(IOAccelShared2*);   // [44]
    virtual void * dirtyLevel(unsigned int, unsigned int);   // [45]
    virtual void * prepare();   // [46]
    virtual void * complete();   // [47]
    virtual void * load();   // [48]
    virtual void * unload();   // [49]
    virtual void * addToChannel(IOAccelChannel2*, unsigned int);   // [50]
    virtual void * removeFromChannel(IOAccelChannel2*);   // [51]
    virtual void * fallback();   // [52]
    virtual void * getResourceInfo(IOAccelGetResourceInfoReturnData*, unsigned int*);   // [53]
    virtual void * pageon(IOAccelEvent*, bool);   // [54]
    virtual void * pageon(IOAccelEvent*, bool, unsigned long long);   // [55]
    virtual void * pageoff(IOAccelEvent*, bool, bool*);   // [56]
    virtual void * pageoff(IOAccelEvent*, bool, bool*, unsigned long long);   // [57]
    virtual void * rebuildPagingBuffer() = 0;   // [58] pure
    virtual void * getMemoryAllocParameter();   // [59]
    virtual void * getLevelOffset(unsigned char, unsigned char, int*) = 0;   // [60] pure
    virtual void * getBackingLevelOffset(unsigned char, unsigned char, int*) = 0;   // [61] pure
    virtual void * calculateIOSurfaceDeviceCacheVRAMBytes(unsigned long long*, unsigned long long*) = 0;   // [62] pure
    virtual void * addToAperture() = 0;   // [63] pure
    virtual void * removeFromAperture() = 0;   // [64] pure
    virtual void * getApertureMemoryDescriptor(unsigned long long*) = 0;   // [65] pure
    virtual void * dirtyFaceLevels(unsigned int, unsigned int);   // [66]
    virtual void * dirtyBufferRange(unsigned int, unsigned int);   // [67]
    virtual void * zeroVidMemory(IOAccelEvent*, unsigned long long);   // [68]
    virtual void * scrubEvents();   // [69]
    virtual void * dirtyBufferRange(unsigned long long, unsigned long long);   // [70]
    virtual void * dirtyVendorCommand(unsigned int, unsigned long long);   // [71]
    virtual void * _RESERVEDIOAccelResource2();   // [72]
    virtual void * _RESERVEDIOAccelResource3();   // [73]
    virtual void * _RESERVEDIOAccelResource4();   // [74]
    virtual void * _RESERVEDIOAccelResource5();   // [75]
    virtual void * pageoffIfNeeded(unsigned int, unsigned int);   // [76]
    virtual void * pageonIfNeeded();   // [77]
    virtual void * gartEvent();   // [78]
protected:
    uint8_t _nvData[0x180 - sizeof(OSObject)];
};
static_assert(sizeof(IOAccelResource2) == 0x180, "IOAccelResource2 layout");

// IOAccelTask : OSObject   sizeof 0x258, 51 vtable slots
class IOAccelTask : public OSObject {
    OSDeclareDefaultStructors(IOAccelTask)
public:
    virtual void release() const;   // [5]
    virtual void free();   // [18]
    virtual bool init(IOGraphicsAccelerator2*, unsigned int, IORangeAllocator**);   // [35]
    virtual void * freeToAllocGPUAddress(IOAccelMemoryMap*);   // [36]
    virtual void * freeAllGPUMappings();   // [37]
    virtual void * freeAllSysMemoryMappings();   // [38]
    virtual void * freeAllVidMemoryMappings();   // [39]
    virtual void * allocate(IOAccelMemoryMap const*);   // [40]
    virtual void * deallocate(IOAccelMemoryMap const*, unsigned long long);   // [41]
    virtual void * reserve(unsigned int, unsigned long long, unsigned long long);   // [42]
    virtual void * describeDriverAllocations(IOAccelAllocationInfo*);   // [43]
    virtual void * _RESERVEDIOAccelTask0();   // [44]
    virtual void * _RESERVEDIOAccelTask1();   // [45]
    virtual void * _RESERVEDIOAccelTask2();   // [46]
    virtual void * _RESERVEDIOAccelTask3();   // [47]
    virtual void * _RESERVEDIOAccelTask4();   // [48]
    virtual void * _RESERVEDIOAccelTask5();   // [49]
    virtual void * freeWaitToAllocGPUAddress(IOAccelMemoryMap*, bool);   // [50]
protected:
    uint8_t _nvData[0x258 - sizeof(OSObject)];
};
static_assert(sizeof(IOAccelTask) == 0x258, "IOAccelTask layout");

// IOAccelSubmitter2 : IOUserClient   sizeof 0x568, 316 vtable slots
class IOAccelSubmitter2 : public IOUserClient {
    OSDeclareDefaultStructors(IOAccelSubmitter2)
public:
    virtual bool start(IOService*);   // [184]
    virtual void stop(IOService*);   // [185]
    virtual void * getOwningTask() const = 0;   // [300] pure
    virtual void * getGPUTask() const = 0;   // [301] pure
    virtual void * getOwningTaskPid() const = 0;   // [302] pure
    virtual void * affectedByHardwareReset(bool, unsigned int) = 0;   // [303] pure
    virtual void * retireCommandBuffer(IOAccelEventFence*);   // [304]
    virtual void * shouldHardwareCommandNooped() = 0;   // [305] pure
    virtual void * orphanClientMappings(OSSet*);   // [306]
    virtual void * setProtectionOptions(unsigned long long);   // [307]
    virtual void * setSubmissionError(unsigned int);   // [308]
    virtual void * _RESERVEDIOAccelSubmitter0();   // [309]
    virtual void * _RESERVEDIOAccelSubmitter1();   // [310]
    virtual void * _RESERVEDIOAccelSubmitter2();   // [311]
    virtual void * _RESERVEDIOAccelSubmitter3();   // [312]
    virtual void * _RESERVEDIOAccelSubmitter4();   // [313]
    virtual void * _RESERVEDIOAccelSubmitter5();   // [314]
    virtual void * isOpportunisticWorkload() const;   // [315]
protected:
    uint8_t _nvData[0x568 - sizeof(IOUserClient)];
};
static_assert(sizeof(IOAccelSubmitter2) == 0x568, "IOAccelSubmitter2 layout");

// IOAccelCommandQueue : IOAccelSubmitter2   sizeof 0x6a8, 337 vtable slots
class IOAccelCommandQueue : public IOAccelSubmitter2 {
    OSDeclareDefaultStructors(IOAccelCommandQueue)
public:
    virtual void free();   // [18]
    virtual bool start(IOService*);   // [184]
    virtual void stop(IOService*);   // [185]
    virtual bool finalize(unsigned int);   // [193]
    virtual bool attach(IOService*);   // [206]
    virtual IOReturn externalMethod(unsigned int, IOExternalMethodArguments*, IOExternalMethodDispatch*, OSObject*, void*);   // [266]
    virtual IOReturn clientClose();   // [286]
    virtual IOReturn connectClient(IOUserClient*);   // [291]
    virtual void * getOwningTask() const;   // [300]
    virtual void * getGPUTask() const;   // [301]
    virtual void * getOwningTaskPid() const;   // [302]
    virtual void * affectedByHardwareReset(bool, unsigned int);   // [303]
    virtual void * retireCommandBuffer(IOAccelEventFence*);   // [304]
    virtual void * shouldHardwareCommandNooped();   // [305]
    virtual void * setSubmissionError(unsigned int);   // [308]
    virtual void * isOpportunisticWorkload() const;   // [315]
    virtual void * commandQueueStart();   // [316]
    virtual void * commandQueueStop();   // [317]
    virtual void * parseSegmentList(IOAccelShared2*, IOAccelSegmentResourceListHeader const*);   // [318]
    virtual void * processSegment(IOAccelSegmentResourceList*, IOAccelKernelCommand const*, IOAccelKernelCommand const*);   // [319]
    virtual void * processSegmentKernelCommands(IOAccelSegmentResourceList*, IOAccelKernelCommand const*, IOAccelKernelCommand const*);   // [320]
    virtual void * processSegmentKernelCommand(IOAccelSegmentResourceList*, IOAccelKernelCommand const*, IOAccelKernelCommand const*);   // [321]
    virtual void * beginCoalescedSegment();   // [322]
    virtual void * endCoalescedSegment();   // [323]
    virtual void * processCommandBuffer(unsigned int, unsigned int);   // [324]
    virtual void * setPriority(eIOAccelCommandQueuePriority);   // [325]
    virtual void * parseSegmentList(IOAccelShared2*, IOAccelSegmentResourceListHeader const*, IOAccelDeviceShmem*);   // [326]
    virtual void * processKernelCommands(IOAccelKernelCommand const*, IOAccelKernelCommand const*);   // [327]
    virtual void * processKernelCommand(IOAccelKernelCommand const*, IOAccelKernelCommand const*);   // [328]
    virtual void * _RESERVEDIOAccelCommandQueue0();   // [329]
    virtual void * _RESERVEDIOAccelCommandQueue1();   // [330]
    virtual void * _RESERVEDIOAccelCommandQueue2();   // [331]
    virtual void * _RESERVEDIOAccelCommandQueue3();   // [332]
    virtual void * _RESERVEDIOAccelCommandQueue4();   // [333]
    virtual void * _RESERVEDIOAccelCommandQueue5();   // [334]
    virtual void * canSubmitCommandBuffer();   // [335]
    virtual void * pauseSubmitCommandBuffer();   // [336]
protected:
    uint8_t _nvData[0x6a8 - sizeof(IOAccelSubmitter2)];
};
static_assert(sizeof(IOAccelCommandQueue) == 0x6a8, "IOAccelCommandQueue layout");

// IOAccelChannel2 : OSObject   sizeof 0x70, 52 vtable slots
class IOAccelChannel2 : public OSObject {
    OSDeclareDefaultStructors(IOAccelChannel2)
public:
    virtual void free();   // [18]
    virtual bool init(IOGraphicsAccelerator2*, int);   // [35]
    virtual void * getFirstPendingEvent() = 0;   // [36] pure
    virtual void * setStampIndex(int);   // [37]
    virtual void * submitCommands(IOAccelCommandDescriptor*) = 0;   // [38] pure
    virtual void * mergeEventExcluding(IOAccelEvent*, IOAccelEvent*);   // [39]
    virtual void * setEventStamp(IOAccelEvent*);   // [40]
    virtual void * incrementStamp();   // [41]
    virtual void * writeStampCommand(IOAccelEventQueue*, vendevtCommandRec*);   // [42]
    virtual void * writeEventBarrierCommand(IOAccelEventQueue*, IOAccelEvent*, vendevtBarrierRec*);   // [43]
    virtual void * restart() = 0;   // [44] pure
    virtual void * submitterDestroyed(IOAccelSubmitter2*);   // [45]
    virtual void * getChannelLabel() const;   // [46]
    virtual void * triage(char**, unsigned long long*);   // [47]
    virtual void * _RESERVEDIOAccelChannel2();   // [48]
    virtual void * _RESERVEDIOAccelChannel3();   // [49]
    virtual void * _RESERVEDIOAccelChannel4();   // [50]
    virtual void * _RESERVEDIOAccelChannel5();   // [51]
protected:
    uint8_t _nvData[0x70 - sizeof(OSObject)];
};
static_assert(sizeof(IOAccelChannel2) == 0x70, "IOAccelChannel2 layout");

// IOAccelFIFOChannel2 : IOAccelChannel2   sizeof 0xe8, 66 vtable slots
class IOAccelFIFOChannel2 : public IOAccelChannel2 {
    OSDeclareDefaultStructors(IOAccelFIFOChannel2)
public:
    virtual void free();   // [18]
    virtual void * getFirstPendingEvent();   // [36]
    virtual void * submitCommands(IOAccelCommandDescriptor*);   // [38]
    virtual void * writeStampCommand(IOAccelEventQueue*, vendevtCommandRec*);   // [42]
    virtual void * restart();   // [44]
    virtual void * submitterDestroyed(IOAccelSubmitter2*);   // [45]
    virtual void * triage(char**, unsigned long long*);   // [47]
    virtual bool init(IOGraphicsAccelerator2*, int, int, int, int);   // [52]
    virtual void * finishChannel();   // [53]
    virtual void * logRingBuffer();   // [54]
    virtual void * pruneRingBuffer();   // [55]
    virtual void * waitForRingBufferSpace();   // [56]
    virtual void * _RESERVEDIOAccelFIFOChannel0();   // [57]
    virtual void * _RESERVEDIOAccelFIFOChannel1();   // [58]
    virtual void * _RESERVEDIOAccelFIFOChannel2();   // [59]
    virtual void * _RESERVEDIOAccelFIFOChannel3();   // [60]
    virtual void * _RESERVEDIOAccelFIFOChannel4();   // [61]
    virtual void * _RESERVEDIOAccelFIFOChannel5();   // [62]
    virtual void * submitBuffer(IOAccelCommandDescriptor*) = 0;   // [63] pure
    virtual void * resetHardwareAndReplay() = 0;   // [64] pure
    virtual void * getHardwareDiagnosisReport(unsigned int*) = 0;   // [65] pure
protected:
    uint8_t _nvData[0xe8 - sizeof(IOAccelChannel2)];
};
static_assert(sizeof(IOAccelFIFOChannel2) == 0xe8, "IOAccelFIFOChannel2 layout");

// IOAccelShared2 : OSObject   sizeof 0x138, 45 vtable slots
class IOAccelShared2 : public OSObject {
    OSDeclareDefaultStructors(IOAccelShared2)
public:
    virtual void free();   // [18]
    virtual bool init(IOGraphicsAccelerator2*, task*);   // [35]
    virtual void * describeDriverAllocations(IOAccelAllocationInfo*);   // [36]
    virtual void * scrubEvents();   // [37]
    virtual void * orphanClientMappings(OSSet*);   // [38]
    virtual void * _RESERVEDIOAccelShared0();   // [39]
    virtual void * _RESERVEDIOAccelShared1();   // [40]
    virtual void * _RESERVEDIOAccelShared2();   // [41]
    virtual void * _RESERVEDIOAccelShared3();   // [42]
    virtual void * _RESERVEDIOAccelShared4();   // [43]
    virtual void * _RESERVEDIOAccelShared5();   // [44]
protected:
    uint8_t _nvData[0x138 - sizeof(OSObject)];
};
static_assert(sizeof(IOAccelShared2) == 0x138, "IOAccelShared2 layout");

// IOAccelSharedUserClient2 : IOUserClient   sizeof 0x168, 308 vtable slots
class IOAccelSharedUserClient2 : public IOUserClient {
    OSDeclareDefaultStructors(IOAccelSharedUserClient2)
public:
    virtual void free();   // [18]
    virtual bool requestTerminate(IOService*, unsigned int);   // [127]
    virtual bool didTerminate(IOService*, unsigned int, bool*);   // [129]
    virtual bool start(IOService*);   // [184]
    virtual void stop(IOService*);   // [185]
    virtual IOReturn externalMethod(unsigned int, IOExternalMethodArguments*, IOExternalMethodDispatch*, OSObject*, void*);   // [266]
    virtual IOReturn clientClose();   // [286]
    virtual IOReturn connectClient(IOUserClient*);   // [291]
    virtual IOExternalMethod * getTargetAndMethodForIndex(IOService**, unsigned int);   // [296]
    virtual void * _RESERVEDIOAccelSharedUserClient0();   // [300]
    virtual void * _RESERVEDIOAccelSharedUserClient1();   // [301]
    virtual void * _RESERVEDIOAccelSharedUserClient2();   // [302]
    virtual void * _RESERVEDIOAccelSharedUserClient3();   // [303]
    virtual void * _RESERVEDIOAccelSharedUserClient4();   // [304]
    virtual void * _RESERVEDIOAccelSharedUserClient5();   // [305]
    virtual void * sharedStart();   // [306]
    virtual void * sharedStop();   // [307]
protected:
    uint8_t _nvData[0x168 - sizeof(IOUserClient)];
};
static_assert(sizeof(IOAccelSharedUserClient2) == 0x168, "IOAccelSharedUserClient2 layout");

// IOAccelDisplayMachine : IOService   sizeof 0x178, 284 vtable slots
class IOAccelDisplayMachine : public IOService {
    OSDeclareDefaultStructors(IOAccelDisplayMachine)
public:
    virtual void free();   // [18]
    virtual bool init(IOGraphicsAccelerator2*);   // [266]
    virtual bool start(IOPCIDevice*);   // [267]
    virtual void stop();   // [268]
    virtual bool displayModeWillChange() = 0;   // [269] pure
    virtual bool displayModeDidChange() = 0;   // [270] pure
    virtual void * initFramebufferResource(unsigned int, unsigned int, IOFramebuffer*, IOAccelResource2*);   // [271]
    virtual void * destroyFramebufferResource(unsigned int, unsigned int, IOFramebuffer*, IOAccelResource2*);   // [272]
    virtual void * triage(char**, unsigned long long*);   // [273]
    virtual void * _RESERVEDIOAccelDisplayMachine1();   // [274]
    virtual void * _RESERVEDIOAccelDisplayMachine2();   // [275]
    virtual void * _RESERVEDIOAccelDisplayMachine3();   // [276]
    virtual void * _RESERVEDIOAccelDisplayMachine4();   // [277]
    virtual void * _RESERVEDIOAccelDisplayMachine5();   // [278]
    virtual void * framebuffer_will_power_off(unsigned int);   // [279]
    virtual void * framebuffer_did_power_on(unsigned int);   // [280]
    virtual void * display_mode_will_change(unsigned int);   // [281]
    virtual void * display_mode_did_change(unsigned int);   // [282]
    virtual void * found_framebuffer(IOFramebuffer*);   // [283]
protected:
    uint8_t _nvData[0x178 - sizeof(IOService)];
};
static_assert(sizeof(IOAccelDisplayMachine) == 0x178, "IOAccelDisplayMachine layout");

