#!/usr/bin/env python3
"""Make drivers/NVGspCore/NVGspBooterUnloadBlob.hpp from NVIDIA's own file.

The SEC2 booter-unload image is NVIDIA firmware, so we don't keep it in the
repo. Grab linux-firmware, point this at nvidia/ad103/gsp/booter_unload-570.144.bin
and it writes the header the kext includes (GSP suspend/resume needs it).

    python3 tools/gen_booter_unload.py /path/to/linux-firmware/nvidia/ad103/gsp/booter_unload-570.144.bin
"""
import hashlib, os, sys

SHA256 = "975b85a14ded8e430d30f000c3c1afdd55c15dee04f35ff9dfd876acd7e67186"
OUT = os.path.join(os.path.dirname(__file__), "..", "drivers", "NVGspCore", "NVGspBooterUnloadBlob.hpp")

if len(sys.argv) != 2:
    raise SystemExit(__doc__)
data = open(sys.argv[1], "rb").read()
if hashlib.sha256(data).hexdigest() != SHA256:
    raise SystemExit("not the 570.144 AD10x booter_unload we tested with (sha256 differs)")
rows = [", ".join(f"0x{b:02x}" for b in data[i:i + 24]) for i in range(0, len(data), 24)]
with open(OUT, "w") as f:
    f.write("#pragma once\n\n// generated by tools/gen_booter_unload.py from NVIDIA's linux-firmware file, do not commit\n")
    f.write("#include <stdint.h>\n\nnamespace nvgsp {\n")
    f.write(f"alignas(16) static const uint8_t kBooterUnloadAd10x[{len(data)}] = {{\n    ")
    f.write(",\n    ".join(rows))
    f.write("\n};\n}\n")
print("wrote", os.path.normpath(OUT), len(data), "bytes")
